// app/page.tsx
'use client';

import { useState, useEffect } from 'react';
import Image from 'next/image';
import { Question } from '@/types';

export default function Home() {
  const [questions, setQuestions] = useState<Question[]>([]);
  const [questionText, setQuestionText] = useState('');
  const [liked, setLiked] = useState<string[]>([]);
  const [activeTab, setActiveTab] = useState<'questions' | 'join'>('questions');
  const [name, setName] = useState('');
  const [mobile, setMobile] = useState('');
  const [isBusy, setIsBusy] = useState(false);

  // Load liked questions from localStorage
  useEffect(() => {
    const storedData = localStorage.getItem('likedComments');
    if (storedData) {
      setLiked(JSON.parse(storedData));
    }
    loadQuestions();
  }, []);

  // Auto-refresh questions every 2 seconds
  useEffect(() => {
    const interval = setInterval(() => {
      loadQuestions();
    }, 2000);

    return () => clearInterval(interval);
  }, []);

  const loadQuestions = async () => {
    try {
      const response = await fetch('/api/question');
      const data = await response.json();
      setQuestions(data);
    } catch (error) {
      console.error('Error loading questions:', error);
    }
  };

  const addQuestion = async () => {
    if (!questionText.trim()) return;

    try {
      const response = await fetch('/api/question', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          questionText: questionText,
        }),
      });

      const data = await response.json();
      setQuestions(data);
      setQuestionText('');
    } catch (error) {
      console.error('Error adding question:', error);
    }
  };

  const likeQuestion = async (id: string, isLike: boolean) => {
    try {
      let updatedLiked = [...liked];

      if (isLike) {
        updatedLiked.push(id);
      } else {
        updatedLiked = updatedLiked.filter(likedId => likedId !== id);
      }

      setLiked(updatedLiked);
      localStorage.setItem('likedComments', JSON.stringify(updatedLiked));

      const response = await fetch('/api/question', {
        method: 'PUT',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          id: id,
          questionText: '',
          noOfLikes: isLike ? 1 : 0,
        }),
      });

      const data = await response.json();
      setQuestions(data);
    } catch (error) {
      console.error('Error liking question:', error);
    }
  };

  const createMember = async () => {
    if (!name.trim() || !mobile.trim()) return;

    setIsBusy(true);
    try {
      await fetch('/api/member', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          name: name,
          mobile: mobile,
        }),
      });

      setName('');
      setMobile('');
      alert('Member registered successfully!');
    } catch (error) {
      console.error('Error creating member:', error);
      alert('Failed to register member');
    } finally {
      setIsBusy(false);
    }
  };

  return (
    <>
      {/* Navigation */}
      <nav className="bg-[#c3094a] text-white fixed w-full z-20 top-0 left-0 border-b border-gray-200">
        <div className="max-w-5xl flex flex-wrap items-center justify-between mx-auto p-2">
          <a href="/" className="flex items-center">
            <Image
              src="/images/malimawa.webp"
              alt="Logo"
              width={40}
              height={40}
              className="h-10 w-10 mr-2"
            />
            <span className="self-center text-2xl font-semibold whitespace-nowrap">
              Ask AKD
            </span>
          </a>
          <a href="https://www.facebook.com/NPPADELAIDE" target="_blank" rel="noopener noreferrer">
            <Image
              src="/images/icons8-facebook.svg"
              alt="Facebook"
              width={40}
              height={40}
              className="h-10 w-10 mr-2"
            />
          </a>
        </div>
      </nav>

      {/* Main Content */}
      <div className="max-w-5xl m-auto mt-20 lg:mt-28 relative px-2 lg:px-0">
        <div className="content">
          {/* Tabs */}
          <div className="border-b border-gray-200 mb-4">
            <nav className="-mb-px flex space-x-8">
              <button
                onClick={() => setActiveTab('questions')}
                className={`${
                  activeTab === 'questions'
                    ? 'border-[#c3094a] text-[#c3094a]'
                    : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300'
                } whitespace-nowrap py-4 px-1 border-b-2 font-medium text-sm uppercase`}
              >
                Ask Questions
              </button>
              <button
                onClick={() => setActiveTab('join')}
                className={`${
                  activeTab === 'join'
                    ? 'border-[#c3094a] text-[#c3094a]'
                    : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300'
                } whitespace-nowrap py-4 px-1 border-b-2 font-medium text-sm uppercase`}
              >
                Join
              </button>
            </nav>
          </div>

          {/* Questions Tab */}
          {activeTab === 'questions' && (
            <div>
              <div className="bg-white overflow-hidden border border-gray-200 rounded shadow grid grid-cols-[1fr_auto] py-4">
                <textarea
                  value={questionText}
                  onChange={(e) => setQuestionText(e.target.value)}
                  placeholder="Type your question..."
                  className="px-4 resize-none outline-none min-h-[40px] max-h-[120px]"
                  rows={1}
                  onInput={(e) => {
                    const target = e.target as HTMLTextAreaElement;
                    target.style.height = 'auto';
                    target.style.height = target.scrollHeight + 'px';
                  }}
                />
              </div>
              <div className="text-right lg:text-left">
                <button
                  disabled={!questionText.trim()}
                  onClick={addQuestion}
                  className="mt-4 py-2 px-6 bg-[#c3094aa2] active:bg-[#c3094a] text-white rounded-full cursor-pointer transition-colors hover:bg-[#c3094a] disabled:opacity-50 disabled:cursor-not-allowed"
                >
                  Send
                </button>
              </div>

              <div className="mt-4 space-y-2">
                {questions.map((question) => (
                  <div
                    key={question.id}
                    className="bg-white overflow-hidden border border-gray-200 rounded-md shadow-sm grid grid-cols-[1fr_auto] place-items-start p-4 text-gray-800 relative text-sm"
                  >
                    <span>{question.questionText}</span>
                    <button className="grid grid-cols-2 place-items-center gap-1">
                      {/* Thumbs up outline (not liked) */}
                      {!liked.includes(question.id) && (
                        <svg
                          onClick={() => likeQuestion(question.id, true)}
                          xmlns="http://www.w3.org/2000/svg"
                          fill="none"
                          viewBox="0 0 24 24"
                          strokeWidth="1.5"
                          stroke="currentColor"
                          className="w-6 h-6 text-[#c3094a] opacity-70 hover:opacity-100 transition-all cursor-pointer"
                        >
                          <path
                            strokeLinecap="round"
                            strokeLinejoin="round"
                            d="M6.633 10.5c.806 0 1.533-.446 2.031-1.08a9.041 9.041 0 012.861-2.4c.723-.384 1.35-.956 1.653-1.715a4.498 4.498 0 00.322-1.672V3a.75.75 0 01.75-.75A2.25 2.25 0 0116.5 4.5c0 1.152-.26 2.243-.723 3.218-.266.558.107 1.282.725 1.282h3.126c1.026 0 1.945.694 2.054 1.715.045.422.068.85.068 1.285a11.95 11.95 0 01-2.649 7.521c-.388.482-.987.729-1.605.729H13.48c-.483 0-.964-.078-1.423-.23l-3.114-1.04a4.501 4.501 0 00-1.423-.23H5.904M14.25 9h2.25M5.904 18.75c.083.205.173.405.27.602.197.4-.078.898-.523.898h-.908c-.889 0-1.713-.518-1.972-1.368a12 12 0 01-.521-3.507c0-1.553.295-3.036.831-4.398C3.387 10.203 4.167 9.75 5 9.75h1.053c.472 0 .745.556.5.96a8.958 8.958 0 00-1.302 4.665c0 1.194.232 2.333.654 3.375z"
                          />
                        </svg>
                      )}
                      {/* Thumbs up filled (liked) */}
                      {liked.includes(question.id) && (
                        <svg
                          onClick={() => likeQuestion(question.id, false)}
                          xmlns="http://www.w3.org/2000/svg"
                          viewBox="0 0 24 24"
                          fill="currentColor"
                          className="w-6 h-6 text-[#c3094a] cursor-pointer"
                        >
                          <path d="M7.493 18.75c-.425 0-.82-.236-.975-.632A7.48 7.48 0 016 15.375c0-1.75.599-3.358 1.602-4.634.151-.192.373-.309.6-.397.473-.183.89-.514 1.212-.924a9.042 9.042 0 012.861-2.4c.723-.384 1.35-.956 1.653-1.715a4.498 4.498 0 00.322-1.672V3a.75.75 0 01.75-.75 2.25 2.25 0 012.25 2.25c0 1.152-.26 2.243-.723 3.218-.266.558.107 1.282.725 1.282h3.126c1.026 0 1.945.694 2.054 1.715.045.422.068.85.068 1.285a11.95 11.95 0 01-2.649 7.521c-.388.482-.987.729-1.605.729H14.23c-.483 0-.964-.078-1.423-.23l-3.114-1.04a4.501 4.501 0 00-1.423-.23h-.777zM2.331 10.977a11.969 11.969 0 00-.831 4.398 12 12 0 00.52 3.507c.26.85 1.084 1.368 1.973 1.368H4.9c.445 0 .72-.498.523-.898a8.963 8.963 0 01-.924-3.977c0-1.708.476-3.305 1.302-4.666.245-.403-.028-.959-.5-.959H4.25c-.832 0-1.612.453-1.918 1.227z" />
                        </svg>
                      )}
                      {question.noOfLikes > 0 && (
                        <span className="text-sm">{question.noOfLikes}</span>
                      )}
                    </button>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Join Tab */}
          {activeTab === 'join' && (
            <div className="bg-white rounded-lg lg:w-2/4 mx-auto p-8 space-y-4">
              <div className="space-y-2">
                <label className="block text-sm font-medium text-gray-700">
                  Name
                </label>
                <input
                  type="text"
                  value={name}
                  onChange={(e) => setName(e.target.value)}
                  className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-[#c3094a]"
                />
              </div>
              <div className="space-y-2">
                <label className="block text-sm font-medium text-gray-700">
                  Mobile
                </label>
                <input
                  type="tel"
                  value={mobile}
                  onChange={(e) => setMobile(e.target.value)}
                  placeholder="555-555-123"
                  className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-[#c3094a]"
                />
              </div>
              <button
                onClick={createMember}
                disabled={!name.trim() || !mobile.trim() || isBusy}
                className="w-full py-2 px-4 bg-[#c3094a] text-white rounded-md hover:bg-[#a00840] transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
              >
                {isBusy ? 'Sending...' : 'Send'}
              </button>
            </div>
          )}

          {/* Header Image */}
          <div className="mt-28">
            <Image
              src="/images/header.jpg"
              alt="Header Image"
              width={1200}
              height={400}
              className="w-full h-auto"
              priority={false}
            />
          </div>

          {/* Footer */}
          <footer className="footer relative mt-4 bg-gray-100 text-center p-3">
            NPP Adelaide
          </footer>
        </div>
      </div>
    </>
  );
}

// angularapp/src/app/app.component.ts
import { HttpClient } from '@angular/common/http';
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {

  public questions?: Question[]
  public liked = new Array();
  public screenSize?: string;
  question: string='';
  public newQuestion?: Question
  private baseUrl = 'http://localhost:5153'

  public name?: string
  public mobile?: string

  isBusy: boolean = false

  constructor(private readonly http: HttpClient) {
    this.loadLikedQuestions();
    this.loadQuestions(); 
  }

  ngAfterViewInit() {
    setInterval(() => {
      this.loadQuestions();
    }, 2000);
  }

  loadQuestions = () =>{
    this.http.get<Question[]>(`${this.baseUrl}/question`).subscribe(result => {
      this.questions = result;
    }, error => console.error(error)    )
  }

  title = 'ASK AKD';

    add =() =>{
      var data = {
        "id": "NEW",
        "questionText": this.question,
        "noOfLikes": 0
      }
     
      this.http.post<Question[]>(`${this.baseUrl}/question`,data).subscribe(result => {
        this.questions = result;
        this.question = '';
      }, error => console.error(error)    )

  }

  clear =() =>{
    this.question='';
  }

  like = (id:number, like: boolean) => {
    var data = {
      "id": id,
      "questionText": '',
      "noOfLikes": like? 1 : 0
    }

    if(like)
    {
      this.liked.push(id);
    }
    else{
      this.liked.splice(this.liked.indexOf(id), 1);
    }

    localStorage.setItem('likedComments', JSON.stringify(this.liked));
   
    this.http.put<Question[]>(`${this.baseUrl}/question`,data).subscribe(result => {
      this.questions = result;
    }, error => console.error(error))
  }

  refresh = () => {
    this.loadQuestions();
  }

   private loadLikedQuestions = () => {
    const storedData = localStorage.getItem('likedComments');
    this.liked= storedData ? JSON.parse(storedData) : [];
  }  

  createMember =() => {

    this.isBusy = true;
    var data = {
      "id": 0,
      "name": this.name,
      "mobile": this.mobile
    }
   
    this.http.post(`${this.baseUrl}/member`,data).subscribe(result => {   
      this.name = '';
      this.mobile=''
    }, error => console.error(error)    )

    this.isBusy = false;
  }
}

interface Question{
  id: number,
  questionText: string
  noOfLikes: number
}
﻿<nav class="bg-[#c3094a] text-white fixed w-full z-20 top-0 left-0 border-b border-gray-200 ">
    <div class="max-w-5xl flex flex-wrap items-center justify-between mx-auto p-2">
    <a href="/" class="flex items-center">
        <img class="h-10 mr-2" src="../assets/imges/malimawa.webp" alt="Logo">
        <span class="self-center text-2xl font-semibold whitespace-nowrap ">Ask AKD</span>
    </a>
    <a href="https://www.facebook.com/NPPADELAIDE"> 
        <img class="h-10 mr-2" src="../assets/imges/icons8-facebook.svg" alt="Logo">
    </a>
    </div>
    </nav>
<div class="max-w-5xl m-auto mt-20 lg:mt-28 relative px-2 lg:px-0"> 
<form class="content mat-body-1">



    <mat-tab-group mat-stretch-tabs="false" mat-align-tabs="start">
        <mat-tab label="Ask Questions" labelClass="">
            <div class="bg-white overflow-hidden border border-gray-200 rounded shadow   grid grid-cols-[1fr_auto] py-4"> 
                <textarea  
                cdkTextareaAutosize
                #autosize="cdkTextareaAutosize"
                cdkAutosizeMinRows="1"
                cdkAutosizeMaxRows="5" [(ngModel)]="question" matInput placeholder="Type your question..." name="question"   class="px-4 resize-none"></textarea>
            </div>
            <div class="text-right lg:text-left">
                <button  [disabled]="!question" class="mt-4 py-2 px-6 bg-[#c3094aa2] active:bg-[#c3094a] text-white rounded-full cursor-pointer transition-colors hover:bg-[#c3094a]" (click)="add()">Send</button>
            </div>
           
            <div class="mt-4 space-y-2">
                <div  *ngFor="let question of questions" class="bg-white overflow-hidden border border-gray-200 rounded-md shadow-sm   grid grid-cols-[1fr_auto] place-items-start p-4 text-gray-800 relative text-sm"> 
                    {{ question.questionText }} 
                    <button class="grid grid-cols-2 place-items-center">
                        <svg (click)="like(question.id,true)" [class.hide]="liked.indexOf(question.id) > -1" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 text-[#c3094a] opacity-70 hover:opacity-100 transition-all">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M6.633 10.5c.806 0 1.533-.446 2.031-1.08a9.041 9.041 0 012.861-2.4c.723-.384 1.35-.956 1.653-1.715a4.498 4.498 0 00.322-1.672V3a.75.75 0 01.75-.75A2.25 2.25 0 0116.5 4.5c0 1.152-.26 2.243-.723 3.218-.266.558.107 1.282.725 1.282h3.126c1.026 0 1.945.694 2.054 1.715.045.422.068.85.068 1.285a11.95 11.95 0 01-2.649 7.521c-.388.482-.987.729-1.605.729H13.48c-.483 0-.964-.078-1.423-.23l-3.114-1.04a4.501 4.501 0 00-1.423-.23H5.904M14.25 9h2.25M5.904 18.75c.083.205.173.405.27.602.197.4-.078.898-.523.898h-.908c-.889 0-1.713-.518-1.972-1.368a12 12 0 01-.521-3.507c0-1.553.295-3.036.831-4.398C3.387 10.203 4.167 9.75 5 9.75h1.053c.472 0 .745.556.5.96a8.958 8.958 0 00-1.302 4.665c0 1.194.232 2.333.654 3.375z" />
                          </svg>
                          <svg (click)="like(question.id,false)" [class.hide]="liked.indexOf(question.id) < 0" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-6 h-6 text-[#c3094a]">
                            <path d="M7.493 18.75c-.425 0-.82-.236-.975-.632A7.48 7.48 0 016 15.375c0-1.75.599-3.358 1.602-4.634.151-.192.373-.309.6-.397.473-.183.89-.514 1.212-.924a9.042 9.042 0 012.861-2.4c.723-.384 1.35-.956 1.653-1.715a4.498 4.498 0 00.322-1.672V3a.75.75 0 01.75-.75 2.25 2.25 0 012.25 2.25c0 1.152-.26 2.243-.723 3.218-.266.558.107 1.282.725 1.282h3.126c1.026 0 1.945.694 2.054 1.715.045.422.068.85.068 1.285a11.95 11.95 0 01-2.649 7.521c-.388.482-.987.729-1.605.729H14.23c-.483 0-.964-.078-1.423-.23l-3.114-1.04a4.501 4.501 0 00-1.423-.23h-.777zM2.331 10.977a11.969 11.969 0 00-.831 4.398 12 12 0 00.52 3.507c.26.85 1.084 1.368 1.973 1.368H4.9c.445 0 .72-.498.523-.898a8.963 8.963 0 01-.924-3.977c0-1.708.476-3.305 1.302-4.666.245-.403-.028-.959-.5-.959H4.25c-.832 0-1.612.453-1.918 1.227z" />
                          </svg>
                          <span *ngIf="question.noOfLikes>0">{{question.noOfLikes}}</span>
                    </button>
                </div> 
            </div>
        </mat-tab>
        <!-- <mat-tab label="Join">
            <div class="">
                
            <div class="bg-white rounded-lg m-5 lg:w-2/4 mx-auto grid grid-cols-1 justify-items-center p-16">
                

                    <mat-form-field class="">
                        <mat-label>Name</mat-label>
                        <input matInput type="text" [(ngModel)]="name" name="name" >        
                      </mat-form-field>
                
    <mat-form-field class="example-full-width">
        <mat-label>Mobile</mat-label>                     
        <input type="tel" matInput placeholder="555-555-123" [(ngModel)]="mobile" name="mobile" > 
      </mat-form-field> 

                  <button mat-raised-button color="primary" [disabled]="!name || !mobile || isBusy" (click)="createMember()">Send</button>
            </div>
        </div>
        </mat-tab> -->
    </mat-tab-group>







    <div class="mt-28">
        <img class="header-image" src="../assets/imges/header.jpg" alt="Header Image">
    </div>

      <footer class="footer relative mt-4">
        NPP Adelaide
      </footer>
</form>



</div>
